import { createClientOptional } from "@/lib/supabase/server"
import { DEMO_CONTENT } from "@/lib/demo-data"
import { DEFAULT_TITLE_STYLES, type TitleStyle } from "@/lib/visual-defaults"

export type ProcessItem = { step: string; title: string; desc: string; image: string }
export type DeliverItem = { title: string; desc: string; image: string; details: string }
export type DividerStyle = { label: string; mode: "color" | "image"; backgroundColor: string; textColor: string; overlay: number; images: string[]; position: string; scale: number }
export type PublicSiteContent = { heroTitle: string; heroAccent: string; heroSubtitle: string; heroAccentIntensity: number; heroImage: string; heroMobileImage: string; heroBackgroundImages: string[]; heroMobileBackgroundImages: string[]; heroOverlayIntensity: number; heroBackgroundPosition: string; heroBackgroundScale: number; heroCardsMotion: number; logo1: string; logo2: string; titleStyles: Record<string, TitleStyle>; dividerStyles: Record<string, DividerStyle>; aboutTitle: string; aboutBody: string; process: ProcessItem[]; delivers: DeliverItem[]; contact: { whatsapp: string; email: string; instagram: string } }
const fallbackProcess: ProcessItem[] = DEMO_CONTENT.process.map((item, index) => ({ ...item, image: ["/portfolio/magia-glass.jpg", "/portfolio/odonto.jpg", "/portfolio/imoveis.jpg", "/portfolio/advocacia.jpg"][index] }))
const fallbackDelivers: DeliverItem[] = DEMO_CONTENT.delivers.map((item, index) => ({ ...item, image: ["/portfolio/magia-glass.jpg", "/portfolio/odonto.jpg", "/portfolio/imoveis.jpg", "/portfolio/advocacia.jpg", "/portfolio/odonto.jpg", "/portfolio/magia-glass.jpg"][index], details: "Conteúdo, estrutura e direção visual definidos para o objetivo do projeto." }))
const fallbackDividers: Record<string, DividerStyle> = { projects: { label: "Projetos em destaque", mode: "color", backgroundColor: "#171717", textColor: "#FFFFFF", overlay: 45, images: [], position: "center center", scale: 100 }, method: { label: "Método · Direção · Resultado", mode: "color", backgroundColor: "#F5F0E8", textColor: "#171717", overlay: 35, images: [], position: "center center", scale: 100 }, presence: { label: "Uma marca que ganha presença", mode: "color", backgroundColor: "#171717", textColor: "#FFFFFF", overlay: 45, images: [], position: "center center", scale: 100 } }
export async function getPublicSiteContent(): Promise<PublicSiteContent> {
  const fallbackImages = ["/portfolio/magia-glass.jpg"]
  const fallback: PublicSiteContent = { heroTitle: "Seu negócio merece uma", heroAccent: "presença digital à altura.", heroSubtitle: DEMO_CONTENT.heroSubtitle, heroAccentIntensity: 100, heroImage: fallbackImages[0], heroMobileImage: "", heroBackgroundImages: fallbackImages, heroMobileBackgroundImages: [], heroOverlayIntensity: 58, heroBackgroundPosition: "center center", heroBackgroundScale: 103, heroCardsMotion: 100, logo1: "/logo-wordmark.png", logo2: "", titleStyles: DEFAULT_TITLE_STYLES, dividerStyles: fallbackDividers, aboutTitle: DEMO_CONTENT.aboutTitle, aboutBody: DEMO_CONTENT.aboutBody, process: fallbackProcess, delivers: fallbackDelivers, contact: { ...DEMO_CONTENT.contact } }
  try {
    const supabase = await createClientOptional(); if (!supabase) return fallback
    const [{ data: content }, { data: settings }] = await Promise.all([supabase.from("site_content").select("key,value"), supabase.from("site_settings").select("key,value")])
    const values = Object.fromEntries((content ?? []).map(row => [row.key, row.value])), config = Object.fromEntries((settings ?? []).map(row => [row.key, row.value]))
    let process = fallback.process, delivers = fallback.delivers
    try { if (values.process_json) process = JSON.parse(values.process_json); if (values.delivers_json) delivers = JSON.parse(values.delivers_json) } catch { process = fallback.process; delivers = fallback.delivers }
    const parseImages = (value: string | undefined, fallbackValue: string[]): string[] => { if (!value) return fallbackValue; try { const parsed: unknown = JSON.parse(value); if (Array.isArray(parsed)) { const images = parsed.filter((item): item is string => typeof item === "string" && !!item.trim()); if (images.length) return images } } catch { if (value.trim()) return [value.trim()] } return fallbackValue }
    const parseJsonObject = <T,>(value: string | undefined, fallbackValue: T): T => { try { return value ? JSON.parse(value) as T : fallbackValue } catch { return fallbackValue } }
    const heroBackgroundImages = parseImages(config.hero_background_images, config.hero_image ? [config.hero_image] : fallback.heroBackgroundImages), heroMobileBackgroundImages = parseImages(config.hero_mobile_background_images, config.hero_mobile_image ? [config.hero_mobile_image] : fallback.heroMobileBackgroundImages)
    return { heroTitle: values.hero_title || fallback.heroTitle, heroAccent: values.hero_accent || fallback.heroAccent, heroSubtitle: values.hero_subtitle || fallback.heroSubtitle, heroAccentIntensity: Math.min(100, Math.max(0, Number(config.hero_accent_intensity || fallback.heroAccentIntensity))), heroImage: config.hero_image || heroBackgroundImages[0] || fallback.heroImage, heroMobileImage: config.hero_mobile_image || heroMobileBackgroundImages[0] || fallback.heroMobileImage, heroBackgroundImages, heroMobileBackgroundImages, heroOverlayIntensity: Math.min(100, Math.max(0, Number(config.hero_overlay_intensity ?? fallback.heroOverlayIntensity))), heroBackgroundPosition: config.hero_background_position || fallback.heroBackgroundPosition, heroBackgroundScale: Math.min(120, Math.max(100, Number(config.hero_background_scale ?? fallback.heroBackgroundScale))), heroCardsMotion: Math.min(100, Math.max(0, Number(config.hero_cards_motion ?? fallback.heroCardsMotion))), logo1: config.logo1 || fallback.logo1, logo2: config.logo2 || fallback.logo2, titleStyles: { ...DEFAULT_TITLE_STYLES, ...parseJsonObject<Record<string, TitleStyle>>(config.title_styles, {}) }, dividerStyles: { ...fallbackDividers, ...parseJsonObject<Record<string, DividerStyle>>(config.divider_styles, {}) }, aboutTitle: values.about_title || fallback.aboutTitle, aboutBody: values.about_body || fallback.aboutBody, process, delivers, contact: { whatsapp: config.whatsapp || fallback.contact.whatsapp, email: config.email || fallback.contact.email, instagram: config.instagram || fallback.contact.instagram } }
  } catch { return fallback }
}
