"use client"
import { Bot, CalendarCheck, PlugZap, ArrowUpRight } from "lucide-react"
import { Reveal, RevealStagger, revealItem } from "@/components/motion/Reveal"
import { motion } from "framer-motion"
import { TitleBlock } from "@/components/TitleBlock"
import { TrackedAnchor } from "@/components/TrackedAnchor"
import type { CommercialSections } from "@/lib/site-content"
import { useReducedMotion } from "@/hooks/useReducedMotion"
const icons=[Bot,CalendarCheck,PlugZap]
export function CommercialSolutions({data,whatsapp}:{data:CommercialSections["solutions"];whatsapp:string}){const reduced=useReducedMotion();const wa=`https://wa.me/${whatsapp}?text=${encodeURIComponent("Olá! Quero saber mais sobre atendimento com IA e integrações para o meu negócio.")}`;return <section id="solucoes" className="bg-white py-20 md:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-7 lg:px-10"><Reveal className="mb-11 max-w-3xl"><p className="vm-eyebrow mb-4">{data.eyebrow}</p><TitleBlock style={{text:data.title,highlight:data.highlight,textColor:"#171717",highlightColor:"#E07A5F",highlightStyle:"color"}} className="!mx-0 !text-left"/><p className="mt-5 max-w-2xl text-lg leading-relaxed text-vm-muted">{data.subtitle}</p></Reveal><RevealStagger className="grid gap-4 md:grid-cols-3">{data.items.map((item,i)=>{const Icon=icons[i]||Bot;return <motion.article key={item.title} variants={reduced?undefined:revealItem} className="rounded-[1.5rem] border border-vm-border bg-vm-bg p-7"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-vm-coral/10 text-vm-coral"><Icon size={20}/></div><h3 className="mt-6 text-xl font-semibold text-vm-ink">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-vm-muted">{item.desc}</p></motion.article>})}</RevealStagger><div className="mt-8 flex flex-wrap gap-2">{data.examples.map(x=><span key={x} className="rounded-full border border-vm-border bg-white px-4 py-2 text-xs text-vm-muted">{x}</span>)}</div><div className="mt-7 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-vm-muted">{data.note}</p><TrackedAnchor href={wa} target="_blank" rel="noopener noreferrer" eventName="solutions_interest" eventMetadata={{location:"solutions_section"}} eventStatus="production" className="inline-flex items-center justify-center gap-2 rounded-full bg-vm-coral px-6 py-3.5 text-sm font-semibold text-white">Conversar sobre o meu negócio<ArrowUpRight size={16}/></TrackedAnchor></div></div></section>}
