"use client"
import { Gauge, FileText, Route, ArrowUpRight } from "lucide-react"
import { Reveal, RevealStagger, revealItem } from "@/components/motion/Reveal"
import { motion } from "framer-motion"
import { TitleBlock } from "@/components/TitleBlock"
import { TrackedAnchor } from "@/components/TrackedAnchor"
import type { CommercialSections } from "@/lib/site-content"
import { useReducedMotion } from "@/hooks/useReducedMotion"
const icons=[Gauge,FileText,Route]
export function CommercialDiagnostic({data,whatsapp}:{data:CommercialSections["diagnostic"];whatsapp:string}){const reduced=useReducedMotion();const wa=`https://wa.me/${whatsapp}?text=${encodeURIComponent("Olá! Gostaria de solicitar o diagnóstico gratuito do meu site: ")}`;return <section id="diagnostico" className="bg-vm-bg py-20 md:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-7 lg:px-10"><div className="rounded-[1.75rem] border border-vm-border bg-vm-sand p-7 md:p-12"><Reveal className="max-w-4xl"><p className="vm-eyebrow mb-4">{data.eyebrow}</p><TitleBlock style={{text:data.title,highlight:data.highlight,textColor:"#171717",highlightColor:"#E07A5F",highlightStyle:"color"}} className="!mx-0 !text-left"/><p className="mt-5 text-lg leading-relaxed text-vm-muted">Uma leitura prática do que seu site comunica e do que ele pode estar deixando escapar.</p></Reveal><RevealStagger className="mt-9 grid gap-4 md:grid-cols-3">{data.items.map((item,i)=>{const Icon=icons[i]||Gauge;return <motion.article key={item.title} variants={reduced?undefined:revealItem} className="rounded-[1.5rem] border border-vm-border bg-white p-6"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-vm-coral/10 text-vm-coral"><Icon size={20}/></div><h3 className="mt-5 text-lg font-semibold text-vm-ink">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-vm-muted">{item.desc}</p></motion.article>})}</RevealStagger><div className="mt-8 flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><TrackedAnchor href={wa} target="_blank" rel="noopener noreferrer" eventName="diagnostic_request" eventMetadata={{location:"diagnostic_section"}} eventStatus="production" className="inline-flex items-center justify-center gap-2 rounded-full bg-vm-coral px-6 py-3.5 text-sm font-semibold text-white">Solicitar avaliação do meu site<ArrowUpRight size={16}/></TrackedAnchor><p className="text-sm text-vm-muted">Ainda não tem site? <a href="#contato" className="font-semibold text-vm-ink hover:text-vm-coral">Fale com a gente</a></p></div></div></div></section>}
